### ISSUE TITLE
Request to upgrade compressor to the latest version

### ISSUE THREAD

**Issue by anangkur** [qiscus/qiscus-multichannel-widget-android#12]
me and my team already using qiscus multichannel widget adroid for years and the experience is already good, until we trying to implement the latest version of [compressor](https://github.com/zetbaitsu/Compressor) library (3.0.1).

qiscus suddenly crash when user trying to select images, here's the error log
```
FATAL EXCEPTION: main
Process: com.kerjaan.app, PID: 25218
java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;)V in class Lid/zelory/compressor/Compressor; or its super classes (declaration of 'id.zelory.compressor.Compressor' appears in /data/app/~~qXkF7FECe8DLKBAAiSoP_Q==/com.kerjaan.app-bHM8ahXuvo5HSf_VBdVIAA==/base.apk!classes5.dex)
	at com.qiscus.multichannel.ui.chat.ChatRoomPresenter.sendFile(ChatRoomPresenter.kt:272)
	at com.qiscus.multichannel.ui.chat.ChatRoomFragment.onActivityResult(ChatRoomFragment.kt:819)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2689)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2669)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:777)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:152)
	at android.app.Activity.dispatchActivityResult(Activity.java:8659)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5939)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

when we downgrade the compressor library to 2.1.1 everything is works again without any problem.

I home qiscus team can upgrade the compressor to the latest version, so my team can also use the latest version of compressor in our project.

**Comment by ariefnurputranto** [comment]
Hi @anangkur, Thanks for report sir.

We will fix it in the next release.

Regards

**Comment by ariefnurputranto** [comment]
hi @anangkur , you can use this version https://github.com/qiscus/qiscus-multichannel-widget-android/releases/tag/2.3.1

Thanks
Regards

**Comment by anangkur** [comment]
thanks for the update @ariefnurputranto ! I think we can close this issue.
