### ISSUE TITLE
got error java.lang.RuntimeException - Please set Qiscus user before start the chatting! from firebase crashlytics

### ISSUE THREAD

**Issue by anangkur** [qiscus/qiscus-multichannel-widget-android#15]
hi Qiscus Team!

Currently, my team and I are trying to fix the issue related to the Qiscus Multichannel Widget library, the details of the issue are as follows:

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {{package_name}/com.qiscus.multichannel.ui.chat.ChatRoomActivity}: java.lang.RuntimeException: Please set Qiscus user before start the chatting!
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4844)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4877)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7941)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
Caused by java.lang.RuntimeException: Please set Qiscus user before start the chatting!
       at com.qiscus.sdk.chat.core.QiscusCore.checkUserSetup(QiscusCore.java:687)
       at com.qiscus.sdk.chat.core.QiscusCore.getQiscusAccount(QiscusCore.java:675)
       at com.qiscus.multichannel.QiscusMultichannelWidget.getQiscusAccount(QiscusMultichannelWidget.kt:208)
       at com.qiscus.multichannel.ui.chat.ChatRoomActivity.onResume(ChatRoomActivity.kt:195)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1531)
       at android.app.Activity.performResume(Activity.java:8422)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4833)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4877)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7941)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```
we got the stack trace from a report made by firebase crashlytics.

this is how we initiate chat in our app

```kotlin
private fun directedToInAppChat() {
    val account = viewModel.getAccount() // get account data from shared preferences
    account?.let {
        //clear user qiscus every open in app chat page
        if (qiscusMultichannelWidget.isLoggedIn()) {
            qiscusMultichannelWidget.clearUser()
        }
        initQiscusAccount(it) 
        initChat(0)
    }
}

private fun initQiscusAccount(account: Account) {
    val userProperties = mapOf()
    qiscusMultichannelWidget.setUser(
        account.phone_number,
        account.name,
        account.selfie_image_url ?: "",
        userProperties
    )
}

private fun initChat(channelId: Int) {
    showLoadingDialog()
    qiscusMultichannelWidget.initiateChat()
        .showLoadingWhenInitiate(false)
        .setChannelId(channelId) // manual set channels id
        .setRoomTitle(getString(R.string.title_qiscus_chat_room))
        .setAvatar(QiscusMultichannelWidgetConfig.Avatar.DISABLE)
        .setRoomSubtitle(
            QiscusMultichannelWidgetConfig.RoomSubtitle.ENABLE,
            null
        )
        .setShowSystemMessage(true)
        .setSessional(false)
        .startChat(requireActivity(), object : QiscusChatRoomBuilder.InitiateCallback {
            override fun onProgress() {}

            override fun onSuccess(
                qChatRoom: QChatRoom,
                qMessage: QMessage?,
                isAutomatic: Boolean,
            ) {
                hideLoadingDialog()
                qiscusMultichannelWidget.openChatRoomById(
                    requireActivity(),
                    qChatRoom.id,
                    true
                ) { throwable ->
                    Toast.makeText(requireContext(), throwable.message, Toast.LENGTH_SHORT).show()
                    throwable.printStackTrace()
                }
            }

            override fun onError(throwable: Throwable) {
                hideLoadingDialog()
                Toast.makeText(requireContext(), throwable.message, Toast.LENGTH_SHORT).show()
            }
        })
}
```

we can make sure that `viewModel.getAccount()` is always return the correct data, because if it is not, it will not continue to `initChat`.

can you help us to find the root cause or maybe give more context about the exception?

**Comment by mmnuradityo** [comment]
Could you please share the implementation in the [application](https://github.com/qiscus/qiscus-multichannel-widget-android/blob/754b2163d8830d17e8dfd4383a45463565dcb7a8/app/src/main/java/com/qiscus/multichannel/sample/widget/SampleApp.kt#L22) layer, specifically at the QiscusMultichannelWidget.setup section? We need to ensure that the "localKey" part is correctly set up.

**Comment by anangkur** [comment]
this is how I setup the `QiscusMultichannelWidget`
```kotlin
private fun setupQiscus() {
      CoroutineScope(Dispatchers.IO).launch {
          qiscusMultiChatEngine = QiscusMultiChatEngine()
          qiscusMultichannelWidget = QiscusMultichannelWidget.setup(
              this@Application,
              qiscusMultiChatEngine.get(QiscusMultiChatEngine.MULTICHANNEL_CORE),
              QiscusUtil.APP_ID,
              QiscusUtil.config(sharedPref),
              QiscusUtil.COLOR,
              QiscusUtil.SECRET_KEY
          )
      }
  }
```

**Comment by mmnuradityo** [comment]
Thank you for the information; we will check it soon.

**Comment by mmnuradityo** [comment]
We have tested using a scenario similar to the code you provided. We recommend removing the `CoroutineScope(Dispatchers.IO).launch` section, as setting up with a different thread can lead to a race condition.

**Comment by anangkur** [comment]
well noted, thanks for your suggestion @mmnuradityo 🙏 I will try to remove `CoroutineScope(Dispatchers.IO).launch`
